#!/usr/bin/env python3
"""Summarize the retained Gazebo teardown core and GDB transcript."""

import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
CASE = (
    ROOT
    / "results/week1/wsl_teardown_crash_debug_20260923"
    / "minimal_5hz_bridge_stop_server_core_20260923_2235"
)

summary = json.loads((CASE / "summary.json").read_text())
backtrace = (CASE / "gdb_backtrace.txt").read_text(errors="replace")
maps = (CASE / "gazebo.maps").read_text(errors="replace")

command_match = re.search(r"Core was generated by `([^']+)'", backtrace)
signal_match = re.search(r"Program terminated with signal ([A-Z0-9]+)", backtrace)
thread_match = re.search(r"Current thread is 1 .*\(LWP (\d+)\)", backtrace)

frames = []
for match in re.finditer(
    r"^#(?P<index>\d+)\s+(?P<address>0x[0-9a-f]+)(?:\s+in\s+)?(?P<detail>.*)$",
    backtrace,
    re.MULTILINE,
):
    frame = {
        "index": int(match.group("index")),
        "address": match.group("address"),
        "detail": match.group("detail").strip(),
    }
    if not any(
        existing["index"] == frame["index"]
        and existing["address"] == frame["address"]
        and existing["detail"] == frame["detail"]
        for existing in frames
    ):
        frames.append(frame)
    if len(frames) >= 10:
        break

interrupted_pc = int("0x000078c1ad754b10", 16)
mapping = None
for line in maps.splitlines():
    match = re.match(r"([0-9a-f]+)-([0-9a-f]+)\s+([rwxps-]+).*?\s(/.*)$", line)
    if not match:
        continue
    start, end = int(match.group(1), 16), int(match.group(2), 16)
    if start <= interrupted_pc < end:
        mapping = {
            "start": f"0x{start:x}",
            "end": f"0x{end:x}",
            "permissions": match.group(3),
            "path": match.group(4),
            "offset_from_mapping_start": interrupted_pc - start,
            "offset_hex": f"0x{interrupted_pc - start:x}",
        }
        break

relevant_library_patterns = (
    "gz-sim-rendering",
    "gz-sim-sensors",
    "gz-sensors-gpu_lidar",
    "gz-sensors-rendering",
    "gz-rendering-ogre2",
    "OgreNext",
    "libgallium",
    "libd3d12core",
    "libd3d12.so",
    "libdxcore",
    "libigd12",
)
loaded_libraries = []
for line in maps.splitlines():
    if any(pattern in line for pattern in relevant_library_patterns):
        path = line.split()[-1]
        if path not in loaded_libraries:
            loaded_libraries.append(path)

analysis = {
    "schema_version": 1,
    "case": summary["name"],
    "core_file": summary["core_files"][0],
    "executable_command": command_match.group(1) if command_match else None,
    "signal": signal_match.group(1) if signal_match else None,
    "crashing_thread_lwp": int(thread_match.group(1)) if thread_match else None,
    "gdb_top_frames": frames,
    "interrupted_frame": {
        "frame": 6,
        "pc": f"0x{interrupted_pc:x}",
        "mapping": mapping,
    },
    "loaded_relevant_libraries": loaded_libraries,
    "classification": {
        "proven": [
            "The crashing executable is gz-sim-main and the terminating signal is SIGSEGV.",
            "The core's selected thread is LWP 25463.",
            "Frames 0-4 are Gazebo fatal-signal backtrace handling through libgcc_s _Unwind_Backtrace.",
            "The interrupted frame below the signal handler is address 0x78c1ad754b10 in WSL libd3d12core.so, offset 0xbb10 from its executable mapping.",
            "Ogre2, gz-rendering, gz-sensors-gpu_lidar, Mesa Gallium, and WSL D3D12 libraries were all loaded.",
        ],
        "likely": [
            "The original fault occurred on a D3D12 rendering worker during Gazebo GPU-LiDAR teardown; the timing and loaded stack are consistent with a rendering-resource lifetime race.",
        ],
        "unknown": [
            "The exact libd3d12core function is unavailable because the WSL graphics library is stripped and no matching debug symbols are installed.",
            "The evidence does not yet identify which Gazebo/Ogre destructor or caller released the D3D12 object.",
            "This core does not establish libgcc_s as the root cause; it is where fatal-signal unwinding faulted or stopped.",
        ],
    },
}

(CASE / "backtrace.json").write_text(json.dumps(analysis, indent=2) + "\n")

frame_rows = "\n".join(
    f"| {frame['index']} | `{frame['address']}` | `{frame['detail'] or 'unknown'}` |"
    for frame in frames
)
library_rows = "\n".join(f"- `{path}`" for path in loaded_libraries)

report = f"""# ARES WSL GPU-LiDAR teardown native backtrace

## Core identity

- Executable: `{analysis['executable_command']}`
- Signal: `{analysis['signal']}`
- Crashing thread: LWP `{analysis['crashing_thread_lwp']}`
- Core: `{analysis['core_file']['path']}` ({analysis['core_file']['size']} bytes)
- GDB transcript: `gdb_backtrace.txt`

## Top frames

| Frame | Address | Symbol / library |
|---:|---|---|
{frame_rows}

The core is selected at `libgcc_s.so.1` while Gazebo's fatal-signal handler is
calling `_Unwind_Backtrace`. The interrupted frame below `<signal handler
called>` is `{analysis['interrupted_frame']['pc']}`. `/proc/<pid>/maps` places
that address in `{mapping['path']}` at executable-mapping offset
`{mapping['offset_hex']}`.

## Relevant loaded libraries

{library_rows}

## PROVEN

""" + "\n".join(f"- {item}" for item in analysis["classification"]["proven"]) + """

## LIKELY

""" + "\n".join(f"- {item}" for item in analysis["classification"]["likely"]) + """

## UNKNOWN

""" + "\n".join(f"- {item}" for item in analysis["classification"]["unknown"]) + "\n"

(CASE / "BACKTRACE_REPORT.md").write_text(report)
print(json.dumps({
    "backtrace_json": str(CASE / "backtrace.json"),
    "report": str(CASE / "BACKTRACE_REPORT.md"),
    "signal": analysis["signal"],
    "interrupted_mapping": mapping,
}))
